swagger: '2.0'
info:
  title: Kenlo ChatGPT Integration API
  description: Uma API que recebe a entrada do usuário, realiza uma integração com o ChatGPT e armazena essa interação em um banco de dados NoSQL (MongoDB)
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:                              
  /questions:
    post:
      tags:
        - questions
      summary: Cadastra uma interação com o ChatGPT
      operationId: PostInteractions
      parameters:
        - in: body
          name: question
          description: A pergunta para o ChatGPT
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      responses:
        201:
          description: Interação criada com sucesso
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              message:
                type: string
                example: This is a ChatGPT interaction
              answer:
                type: string
                example: This is a ChatGPT interaction response
              __v:
                type: integer
                example: 0
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
        503:
          description: Service Unavailable
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              message:
                type: string
                example: This is a ChatGPT interaction
              answer:
                type: string
                example: This is a ChatGPT interaction response
              __v:
                type: integer
                example: 0
        400:
          description: Invalid Request
          schema:
            $ref: '#/definitions/BadRequest'
    get:
      tags:
        - questions
      summary: Retorna as interações feitas com o ChatGPT
      operationId: GetInteractions
      responses:
        200:
          description: ChatGPT Interaction
          schema:
            type: object
            properties:
              interactions:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 6467f4b1814cc36532fc67be
                    message:
                      type: string
                      example: ChatGPT question
                    answer:
                      type: string
                      example: ChatGPT answer
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
  
definitions:
  InternalServerError:
    properties:   
      statusCode:
        type: number
        example: 500
      message:
        type: string
        example: 'Error code: 1100'
      error:
        type: string
        example: Internal Server Error
  BadRequest:
    properties:   
      statusCode:
        type: number
        example: 400
      message:
        type: array
        items:
          type: string
          example: field must not be empty.
      error:
        type: string
        example: Bad Request
